# Generated by Django 4.2.15 on 2025-02-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='phone',
        ),
    ]
