# Generated by Django 4.2.15 on 2025-01-30 09:15

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Select User Gender', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
    ]
