# Generated by Django 4.2.15 on 2025-01-16 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import salad.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Ingredient name', max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per kg', max_digits=10, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, help_text='Calories per 100gram', max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kilograms (kg)', max_digits=6, null=True)),
                ('category', models.CharField(blank=True, choices=[('base', 'Base'), ('vegetable', 'Vegetable'), ('topping', 'Topping'), ('dressing', 'Dressing'), ('extra', 'Extra')], help_text='Ingredient category', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Ingredient description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of the ingredient', null=True, upload_to=salad.models.upload_location)),
                ('available', models.BooleanField(default=True, help_text='Is available?')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'salad_ingredient',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Salad name', max_length=250, null=True)),
                ('description', models.TextField(blank=True, help_text='Salad description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of the salad', null=True, upload_to=salad.models.upload_location)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Salad price', max_digits=10, null=True)),
                ('available', models.BooleanField(default=True, help_text='Is salad available?')),
                ('salad_type', models.CharField(choices=[('most_loved', 'Most Loved Salad'), ('popular_pick', 'Popular Salad Pick')], help_text='Salad type', max_length=20)),
                ('ingredients', models.ManyToManyField(help_text='Ingredients in the salad', related_name='salads', to='salad.ingredient')),
            ],
            options={
                'verbose_name': 'Salad',
                'verbose_name_plural': 'Salads',
                'db_table': 'salad',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating between 1 and 5')),
                ('comment', models.TextField(blank=True, help_text='Review comment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='salad.salad')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'salad_review',
            },
        ),
    ]
