# Generated by Django 4.2.15 on 2025-03-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Calories per 100gram', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Price per kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_calories',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total calories of the recipe', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Total price of the order', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='calories',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Calories based on weight', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Price based on weight', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.25, help_text='Weight in kg (default 250g)', max_digits=10),
        ),
    ]
