# Generated by Django 4.2.15 on 2025-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
