# Generated by Django 4.2.15 on 2025-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salad', '0002_alter_salad_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'placed'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', help_text='Status of the order', max_length=20),
        ),
    ]
