# Generated by Django 4.2.15 on 2025-03-03 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salad', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Recipe name', max_length=250, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price of the order', max_digits=10)),
                ('ingredients', models.ManyToManyField(help_text='Ingredients in the custom order', related_name='recipe', to='salad.ingredient')),
                ('user', models.ForeignKey(help_text='The user who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
